import type { GiftAttackDefinition } from "./types";

export const GIFT_ATTACKS: GiftAttackDefinition[] = [
  {
    id: "rose_missile",
    tiktokGiftName: "Rose",
    label: "Rose Missile",
    icon: "RO",
    tier: "micro",
    damage: 24,
    cooldownMs: 1800,
    targetMode: "nearest",
    animationType: "missile",
    description: "Launches a fast single-target missile at the nearest enemy.",
    handler: "smallMissile",
  },
  {
    id: "like_burst",
    tiktokGiftName: "Like Burst",
    label: "Bullet Storm",
    icon: "LB",
    tier: "micro",
    damage: 8,
    cooldownMs: 2400,
    targetMode: "enemyTeam",
    animationType: "bulletStorm",
    description: "Sprays low-damage bullets across the enemy front line.",
    handler: "bulletStorm",
  },
  {
    id: "follow_boost",
    tiktokGiftName: "Follow",
    label: "Boosted Unit",
    icon: "FU",
    tier: "standard",
    damage: 12,
    cooldownMs: 4200,
    targetMode: "selfTeam",
    animationType: "hook",
    description: "Spawns a boosted follower unit and throws a quick hook at the enemy front.",
    handler: "boostedUnit",
  },
  {
    id: "paper_crane_thunder",
    tiktokGiftName: "Paper Crane",
    label: "Thunder Bridge",
    icon: "PC",
    tier: "standard",
    damage: 34,
    cooldownMs: 5200,
    targetMode: "line",
    animationType: "thunderBridge",
    description: "Connects both sides with a lightning bridge that shocks enemies.",
    handler: "thunderBridge",
  },
  {
    id: "doughnut_tornado",
    tiktokGiftName: "Doughnut",
    label: "Tornado",
    icon: "DO",
    tier: "standard",
    damage: 38,
    cooldownMs: 6200,
    targetMode: "area",
    animationType: "tornado",
    description: "Drops a rotating vortex that chips and drags enemy players.",
    handler: "tornado",
  },
  {
    id: "fire_lotus_aoe",
    tiktokGiftName: "Fire Lotus",
    label: "Fire Lotus",
    icon: "FL",
    tier: "heavy",
    damage: 48,
    cooldownMs: 7600,
    targetMode: "area",
    animationType: "fireAoe",
    description: "Creates a circular fire area with heavy burst damage.",
    handler: "fireAoe",
  },
  {
    id: "dragon_palm_wave",
    tiktokGiftName: "Dragon Palm",
    label: "Dragon Palm",
    icon: "DP",
    tier: "heavy",
    damage: 42,
    cooldownMs: 8400,
    targetMode: "enemyTeam",
    animationType: "knockbackWave",
    description: "Sends a knockback wave through the enemy formation.",
    handler: "knockbackWave",
  },
  {
    id: "meteor_shower",
    tiktokGiftName: "Meteor Shower",
    label: "Meteor Shower",
    icon: "MS",
    tier: "legendary",
    damage: 58,
    cooldownMs: 11_000,
    targetMode: "randomEnemy",
    animationType: "meteorShower",
    description: "Drops random bombs over the enemy half of the arena.",
    handler: "meteorShower",
  },
  {
    id: "galaxy_laser",
    tiktokGiftName: "Galaxy",
    label: "Galaxy Laser",
    icon: "GA",
    tier: "legendary",
    damage: 78,
    cooldownMs: 14_000,
    targetMode: "line",
    animationType: "laser",
    description: "Fires a giant horizontal laser through clustered enemies.",
    handler: "giantLaser",
  },
  {
    id: "lion_universe_ultimate",
    tiktokGiftName: "Lion/Universe",
    label: "Ultimate Roar",
    icon: "UL",
    tier: "ultimate",
    damage: 105,
    cooldownMs: 22_000,
    targetMode: "allEnemies",
    animationType: "ultimate",
    description: "Triggers a screen-wide ultimate strike with camera shake.",
    handler: "ultimateScreenAttack",
  },
  {
    id: "all_combo",
    tiktokGiftName: "All Combo",
    label: "All Combo",
    icon: "AC",
    tier: "ultimate",
    damage: 62,
    cooldownMs: 19_000,
    targetMode: "enemyTeam",
    animationType: "combo",
    description: "Chains missiles, lightning, bombs, and a final blast.",
    handler: "comboChain",
  },
  {
    id: "all_plus_one_win",
    tiktokGiftName: "All +1 Win",
    label: "+1 Win",
    icon: "+1",
    tier: "ultimate",
    damage: 0,
    cooldownMs: 15_000,
    targetMode: "score",
    animationType: "scorePulse",
    description: "Adds one direct score to the gifting team.",
    handler: "directScore",
  },
];

export const GIFT_BY_ID = Object.fromEntries(GIFT_ATTACKS.map((gift) => [gift.id, gift]));

export function getGiftByName(name: string) {
  const normalized = name.trim().toLowerCase();
  return GIFT_ATTACKS.find((gift) => gift.tiktokGiftName.toLowerCase() === normalized);
}
